// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that suggests improvements to a prompt to improve image modification results.
 *
 * - improvePromptClarity - A function that suggests improvements to the prompt.
 * - ImprovePromptClarityInput - The input type for the improvePromptClarity function.
 * - ImprovePromptClarityOutput - The return type for the improvePromptClarity function.
 */

import {genkit} from 'genkit';
import {googleAI} from '@genkit-ai/googleai';
import {z} from 'genkit';

const ImprovePromptClarityInputSchema = z.object({
  prompt: z.string().describe('The prompt to be improved.'),
  imageDescription: z.string().optional().describe('A description of the image to be modified.'),
  apiKey: z.string().describe('User-provided Google AI API key.'),
});
export type ImprovePromptClarityInput = z.infer<typeof ImprovePromptClarityInputSchema>;

const ImprovePromptClarityOutputSchema = z.object({
  improvedPrompt: z.string().describe('The improved prompt.'),
  reasoning: z.string().describe('The reasoning behind the suggested improvements.'),
});
export type ImprovePromptClarityOutput = z.infer<typeof ImprovePromptClarityOutputSchema>;

export async function improvePromptClarity(input: ImprovePromptClarityInput): Promise<ImprovePromptClarityOutput> {
  const genAI = genkit({
    plugins: [googleAI({ apiKey: input.apiKey, apiVersion: 'v1beta' })],
  });

  const promptTemplate = `You are an AI prompt engineer specializing in improving prompts for image modification.

Given the original prompt and an optional description of the image to be modified, suggest improvements to the prompt to achieve better image modification results.

Original Prompt: {{{prompt}}}
Image Description: {{#if imageDescription}}{{{imageDescription}}}{{else}}No image description provided.{{/if}}

Provide the improved prompt and explain the reasoning behind the changes.

The improved prompt should be clear, concise, and specific.
The reasoning should explain why the changes were made and how they will improve the results.
`;

  const prompt = genAI.definePrompt({
    name: 'improvePromptClarityPrompt',
    model: 'googleai/gemini-1.5-pro-latest',
    input: {schema: ImprovePromptClarityInputSchema},
    output: {schema: ImprovePromptClarityOutputSchema},
    prompt: promptTemplate,
  });

  const {output} = await prompt(input);
  return output!;
}
